### ISSUE TITLE
项目初始资料咨询

### ISSUE THREAD

**Issue by Penge666** [ViolaPioggia/GoYin#18]
请问下项目运行起来需要什么资料呢？想咨询下

**Comment by ViolaPioggia** [comment]
有挺多的，以 user 模块为例可以参考文件代码 server/service/user/config 和 server/service/user/main.go

**Comment by Penge666** [comment]
请问下这个项目前端的部分吗？能否留个邮箱咨询下呢。谢谢

**Comment by ViolaPioggia** [comment]
这个项目的前端部分是青训营给的 app 我也没有，邮箱的话我这个 github 账号就可以
